### ISSUE TITLE
No nodes responded

### ISSUE THREAD

**Issue by Huddie** [mafintosh/peer-network#5]
I get a` No nodes responded` error right off the bat in the example project. Any idea @mafintosh

**Comment by Huddie** [comment]
```
at QueryStream._finalize (/path/node_modules/dht-rpc/query-stream.js:76:56)
    at QueryStream._sendTokens (/path/node_modules/dht-rpc/query-stream.js:109:8)
    at QueryStream._sendPending (/path/node_modules/dht-rpc/query-stream.js:122:10)
    at QueryStream._read (/path/node_modules/dht-rpc/query-stream.js:130:13)
    at QueryStream._readMaybe (/path/node_modules/dht-rpc/query-stream.js:100:50)
    at QueryStream._callback (/path/node_modules/dht-rpc/query-stream.js:153:10)
    at Object.onresponseholepunch [as callback] (/path/node_modules/dht-rpc/query-stream.js:53:47)
    at UDP._cancel (/path/node_modules/udp-request/index.js:149:7)
    at UDP._checkTimeouts (/path/node_modules/udp-request/index.js:194:10)
    at Timeout.kick [as _onTimeout] (/path/node_modules/udp-request/index.js:58:10)
```

**Comment by opensourcer2** [comment]
@mafintosh Is there any solution for this error?

**Comment by Deepp0925** [comment]
@Huddie have u found a solution for this?

**Comment by draeder** [comment]
This project appears to have build errors: https://travis-ci.org/github/mafintosh/peer-network. I wasn't able to get it working locally either.
